/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Diego
 */
public class Form_principal extends javax.swing.JFrame {

    /**
     * Creates new form Form_inicio
     */
    public Form_principal() {
       initComponents();
       this.setExtendedState(Form_principal.MAXIMIZED_BOTH);
       this.setTitle("Sistema de Gestion Universitaria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnusistema = new javax.swing.JMenu();
        mnuaplicacion = new javax.swing.JMenu();
        aluMenuItem = new javax.swing.JMenuItem();
        profMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(102, 204, 255));

        mnusistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio.png"))); // NOI18N
        mnusistema.setMnemonic('f');
        mnusistema.setText("Sistema SGA_Java");
        menuBar.add(mnusistema);

        mnuaplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Archivo.png"))); // NOI18N
        mnuaplicacion.setMnemonic('e');
        mnuaplicacion.setText("Aplicaciones");

        aluMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aluMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajadores.png"))); // NOI18N
        aluMenuItem.setMnemonic('t');
        aluMenuItem.setText("Alumno");
        mnuaplicacion.add(aluMenuItem);

        profMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        profMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/habitaciones.png"))); // NOI18N
        profMenuItem.setMnemonic('y');
        profMenuItem.setText("Profesores");
        profMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profMenuItemActionPerformed(evt);
            }
        });
        mnuaplicacion.add(profMenuItem);

        pasteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        pasteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Reservas.png"))); // NOI18N
        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Materias");
        mnuaplicacion.add(pasteMenuItem);

        deleteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        deleteMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salir.png"))); // NOI18N
        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Salir");
        mnuaplicacion.add(deleteMenuItem);

        menuBar.add(mnuaplicacion);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ayuda.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Configuraciones.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Ayuda");
        contentMenuItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contentMenuItemKeyTyped(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio.png"))); // NOI18N
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Acerca de..");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salir.png"))); // NOI18N
        jMenu1.setText("Salir");
        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profMenuItemActionPerformed
        Form_profesor form=new  Form_profesor();
        escritorio.add(form);
        form.toFront();
        form.setVisible(true);
        form.show();
        
    }//GEN-LAST:event_profMenuItemActionPerformed

    private void contentMenuItemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contentMenuItemKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_contentMenuItemKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    public javax.swing.JMenuItem aluMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu mnuaplicacion;
    private javax.swing.JMenu mnusistema;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem profMenuItem;
    // End of variables declaration//GEN-END:variables

}
